<?php
// 

/**
 * @file
 * Enables Drupal to send e-mail using the PostageApp API.
 *
 * Overriding mail handling in Drupal requires setting the smtp_library
 * variable with the filename of a file containing a drupal_mail_wrapper()
 * function. This module sets the smtp_library value to point back to this
 * file which contains the drupal_mail_wrapper() function that uses the
 * PHPMailer class to send e-mail instead of the PHP mail() function.
 *
 * @author Stephen McLeod
 * @link http://postageapp.com
 * @version $Id$
 */



require_once('PostageApp.class.php');

/**
* Implementation of hook_help().
*/
function postageapp_help($path, $arg) {
 $output = '';
 switch ($path) {
   case "admin/help#postageapp":
     $output = '<p>'.  t("Allows you to send mail using the PostageApp API.  See http://postageapp.com for more info.") .'</p>';
     break;
 }
 return $output;
} // End of postageapp_help()

/**
 * Implementation of hook_menu
 */
function postageapp_menu() {
  $items = array();
  
  $items['admin/settings/postageapp'] = array(
    'title' => 'PostageApp settings',
    'description' => t('Settings for PostageApp integration'),
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('postageapp_admin_form'),
    'access arguments' => array('administer postageapp'),
    'file' => 'postageapp.admin.inc',
  );
  
  return $items;
} // End of postageapp_menu()

/**
 * Implementation of hook_perm
 */
function postageapp_perm() {
  return array('administer postageapp');
} // End of postageapp_perm()

/**
* Override the mail function
* so we can send mail using the postageapp API
*/
function drupal_mail_wrapper($message) {
  if ($message['from']) {
    $headers = array_merge($message['headers'], array('From' => $message['from']));
    $headers = array_merge($message['headers'], array('Reply-to' => $message['from']));
  } else {
    $headers = $message['headers'];
  }

  $q = new PostageApp(variable_get('postageapp_api_key', '')); 
  $return = $q->mail(
    $message['to'], 
    $message['subject'], 
    $message['body'],
    $headers
  );
  
  if (!($return->response->status == 'ok')) {
    watchdog('mail', 'Error sending e-mail (from %from to %to).', array('%from' => $message['from'], '%to' => $message['to']), WATCHDOG_ERROR);
    drupal_set_message(t($return->data->message), 'error');
  }
  
  return $return;
}
?>